on: push

jobs:
  job1:
    runs-on: macos-latest
    steps:
      - run: echo '#include <stdio.h>' > main.c
      - run: echo 'int main(void) {' >> main.c
      - run: echo 'printf("hello, macos\n");' >> main.c
      - run: echo 'return 0;' >> main.c
      - run: echo '}' >> main.c
      - run: gcc -S main.c
      - run: cat main.s
